// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eztemloezduoapfvwenv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dGVtbG9lemR1b2FwZnZ3ZW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDMwNzksImV4cCI6MjA3Mzk3OTA3OX0.kNbI-woV3K2UGAJ4zJQ7HJfXgcRB7Vt3QyaokHRKiC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});